[package]
name = "oml-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]] 
name="oml-audio"
path="src/oml_audio_main.rs"

[dependencies]

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
